force-app/main/default/objects/N_S_cio_Seria_o__c/N_S_cio_Seria_o__c.object-meta.xml
<CustomObject>
    <label>Nº Sócio - Seriação</label>
    <nameField>
        <label>Nome de ASDDSA</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Nº Sócio - Seriações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/N_S_cio_Seria_o__c/fields/Letra__c.field-meta.xml
<CustomField>
    <fullName>Letra__c</fullName>
    <label>Letra</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>D</fullName>
            </value>
            <value>
                <fullName>E</fullName>
            </value>
            <value>
                <fullName>F</fullName>
            </value>
            <value>
                <fullName>G</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>I</fullName>
            </value>
            <value>
                <fullName>J</fullName>
            </value>
            <value>
                <fullName>K</fullName>
            </value>
            <value>
                <fullName>L</fullName>
            </value>
            <value>
                <fullName>M</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
            <value>
                <fullName>O</fullName>
            </value>
            <value>
                <fullName>P</fullName>
            </value>
            <value>
                <fullName>Q</fullName>
            </value>
            <value>
                <fullName>R</fullName>
            </value>
            <value>
                <fullName>S</fullName>
            </value>
            <value>
                <fullName>T</fullName>
            </value>
            <value>
                <fullName>U</fullName>
            </value>
            <value>
                <fullName>V</fullName>
            </value>
            <value>
                <fullName>X</fullName>
            </value>
            <value>
                <fullName>Z</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/N_S_cio_Seria_o__c/fields/Tipo_de_S_cio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_S_cio__c</fullName>
    <label>Tipo de Sócio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Efetivos</fullName>
            </value>
            <value>
                <fullName>Cooperante</fullName>
                <label>Cooperante pessoa singular</label>
            </value>
            <value>
                <fullName>Cooperante pessoa coletiva</fullName>
            </value>
            <value>
                <fullName>Honorários</fullName>
                <label>Honorário</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/N_S_cio_Seria_o__c/fields/ultimo_n_mero__c.field-meta.xml
<CustomField>
    <fullName>ultimo_n_mero__c</fullName>
    <label>ultimo número</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/updateNumSocioTest.cls
@isTest
public class updateNumSocioTest {
    
    
    @testSetup
    public static void setup(){
        
        N_S_cio_Seria_o__c serieTestA = new N_S_cio_Seria_o__c (Tipo_de_S_cio__c = 'Efetivos', Letra__c = 'A', ultimo_n_mero__c = 1);
        insert serieTestA;
         N_S_cio_Seria_o__c serieTestB = new N_S_cio_Seria_o__c (Tipo_de_S_cio__c = 'Cooperante', Letra__c = 'B', ultimo_n_mero__c = 1);
        insert serieTestB;
         N_S_cio_Seria_o__c serieTestC = new N_S_cio_Seria_o__c (Tipo_de_S_cio__c = 'Cooperante pessoa coletiva', Letra__c = 'C', ultimo_n_mero__c = 1);
        insert serieTestC;
        
        
    }

    @isTest
    public static void test(){
        insert new Contact(
        	LastName = 'teste',
            Data_de_admiss_o__c = date.today(),
            Tipo_de_S_cio__c = 'Efetivos'
        );
        
        insert new Contact(
        	lastname = 'teste 2',
            Data_de_admiss_o__c = date.today(),
            Tipo_de_S_cio__c = 'Cooperante'
        );
        
        insert new Contact(
            lastname = 'teste 3',
             Data_de_admiss_o__c = date.today(),
             Tipo_de_S_cio__c = 'Cooperante pessoa coletiva',
              BI_CC__c  = '232312332'
        );
        
        
    }
    
    @isTest 
    public static void updateTest(){
        

        Contact t = new Contact(
            lastname = 'teste 3',
             Data_de_admiss_o__c = date.today(),
             Tipo_de_S_cio__c = 'Cooperante pessoa coletiva',
              BI_CC__c  = '232312332'
        );
        insert t;

        t.Tipo_de_S_cio__c = 'Cooperante';
        
        update t;

        
    }
   
}